/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pertanianpbo;

/**
 *
 * @author RadityaMN
 */
public class editprofil extends javax.swing.JFrame {

    /**
     * Creates new form editprofil
     */
    public editprofil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        produk = new javax.swing.JLabel();
        pekerjaan = new javax.swing.JTextField();
        perempuan = new javax.swing.JRadioButton();
        lakilaki = new javax.swing.JRadioButton();
        tanggallahir = new com.toedter.calendar.JDateChooser();
        nama = new javax.swing.JTextField();
        notelp = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        produk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                produkMouseClicked(evt);
            }
        });
        getContentPane().add(produk, new org.netbeans.lib.awtextra.AbsoluteConstraints(1025, 456, 170, 150));

        pekerjaan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        pekerjaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pekerjaanActionPerformed(evt);
            }
        });
        getContentPane().add(pekerjaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 490, 40));

        perempuan.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        perempuan.setForeground(new java.awt.Color(255, 255, 255));
        perempuan.setText("perempuan");
        getContentPane().add(perempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, -1, -1));

        lakilaki.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lakilaki.setForeground(new java.awt.Color(255, 255, 255));
        lakilaki.setText("laki - laki");
        getContentPane().add(lakilaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, -1, -1));
        getContentPane().add(tanggallahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 490, -1));

        nama.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 490, 40));

        notelp.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        getContentPane().add(notelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 490, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/13.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pekerjaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pekerjaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pekerjaanActionPerformed

    private void produkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produkMouseClicked
      new produk().setVisible(true);
      this.dispose();//
    }//GEN-LAST:event_produkMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editprofil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editprofil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editprofil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editprofil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editprofil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JRadioButton lakilaki;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField notelp;
    private javax.swing.JTextField pekerjaan;
    private javax.swing.JRadioButton perempuan;
    private javax.swing.JLabel produk;
    private com.toedter.calendar.JDateChooser tanggallahir;
    // End of variables declaration//GEN-END:variables
}
