/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pertanianpbo;

/**
 *
 * @author RadityaMN
 */
public class invest2 extends javax.swing.JFrame {

    /**
     * Creates new form invest2
     */
    public invest2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        atasnama = new javax.swing.JTextField();
        noktp = new javax.swing.JTextField();
        cabang = new javax.swing.JTextField();
        npwp = new javax.swing.JTextField();
        norekening = new javax.swing.JTextField();
        checkbox1 = new java.awt.Checkbox();
        checkbox2 = new java.awt.Checkbox();
        checkbox3 = new java.awt.Checkbox();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(955, 586, 160, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BCA", "BRI", "BNI", "BTN", "CIMB", "Mandiri", " " }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 380, -1));

        atasnama.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        getContentPane().add(atasnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 350, 380, 40));

        noktp.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        getContentPane().add(noktp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 380, 40));

        cabang.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        getContentPane().add(cabang, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 280, 380, 40));

        npwp.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        getContentPane().add(npwp, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 440, 380, 40));

        norekening.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        getContentPane().add(norekening, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 380, 40));

        checkbox1.setLabel("Saya juga menyatakan bahwa iFram berhak melakukan pengecekan terhadap kebenaran data saya");
        getContentPane().add(checkbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 690, -1));

        checkbox2.setLabel("Alokasikan keuntungan untuk wakaf*");
        getContentPane().add(checkbox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 260, -1));

        checkbox3.setLabel("Saya menyatakan data diatas adalah benar, dan sudah saya lakukan pengecekan terhadap setiap pointnya");
        getContentPane().add(checkbox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 690, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/15.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
      new perjanjian().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(invest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(invest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(invest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(invest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new invest2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField atasnama;
    private javax.swing.JLabel background;
    private javax.swing.JTextField cabang;
    private java.awt.Checkbox checkbox1;
    private java.awt.Checkbox checkbox2;
    private java.awt.Checkbox checkbox3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField noktp;
    private javax.swing.JTextField norekening;
    private javax.swing.JTextField npwp;
    // End of variables declaration//GEN-END:variables
}
