/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pertanianpbo;

/**
 *
 * @author RadityaMN
 */
public class produk extends javax.swing.JFrame {

    /**
     * Creates new form produk
     */
    public produk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Akar = new javax.swing.JLabel();
        Sukun = new javax.swing.JLabel();
        Cengkeh = new javax.swing.JLabel();
        Lada = new javax.swing.JLabel();
        alurkerja = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Akar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AkarMouseClicked(evt);
            }
        });
        getContentPane().add(Akar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 220, 250, 380));

        Sukun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SukunMouseClicked(evt);
            }
        });
        getContentPane().add(Sukun, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 250, 380));

        Cengkeh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CengkehMouseClicked(evt);
            }
        });
        getContentPane().add(Cengkeh, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 250, 380));

        Lada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LadaMouseClicked(evt);
            }
        });
        getContentPane().add(Lada, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 226, 250, 370));
        getContentPane().add(alurkerja, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 80, 70));

        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });
        getContentPane().add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 80, 80));

        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 46, 80, 70));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/5.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LadaMouseClicked
      new Lada().setVisible(true);
      this.dispose();//
    }//GEN-LAST:event_LadaMouseClicked

    private void CengkehMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CengkehMouseClicked
      new Cengkeh().setVisible(true);
      this.dispose();//
    }//GEN-LAST:event_CengkehMouseClicked

    private void SukunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SukunMouseClicked
      new Sukun().setVisible(true);
      this.dispose();//
    }//GEN-LAST:event_SukunMouseClicked

    private void AkarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AkarMouseClicked
      new Akar().setVisible(true);
      this.dispose();//
    }//GEN-LAST:event_AkarMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
      new home().setVisible(true);
      this.dispose();//
    }//GEN-LAST:event_homeMouseClicked

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
      new profile().setVisible(true);
      this.dispose();//
    }//GEN-LAST:event_profileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(produk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new produk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Akar;
    private javax.swing.JLabel Cengkeh;
    private javax.swing.JLabel Lada;
    private javax.swing.JLabel Sukun;
    private javax.swing.JLabel alurkerja;
    private javax.swing.JLabel background;
    private javax.swing.JLabel home;
    private javax.swing.JLabel profile;
    // End of variables declaration//GEN-END:variables
}
